#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace book.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="book")]
	public partial class bookDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertleixingbiao(leixingbiao instance);
    partial void Updateleixingbiao(leixingbiao instance);
    partial void Deleteleixingbiao(leixingbiao instance);
    partial void Insertlog(log instance);
    partial void Updatelog(log instance);
    partial void Deletelog(log instance);
    partial void Insertjiehuanbiao(jiehuanbiao instance);
    partial void Updatejiehuanbiao(jiehuanbiao instance);
    partial void Deletejiehuanbiao(jiehuanbiao instance);
    partial void Inserttushubiao(tushubiao instance);
    partial void Updatetushubiao(tushubiao instance);
    partial void Deletetushubiao(tushubiao instance);
    partial void Insertcuihuanbiao(cuihuanbiao instance);
    partial void Updatecuihuanbiao(cuihuanbiao instance);
    partial void Deletecuihuanbiao(cuihuanbiao instance);
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void Insertkehubiao(kehubiao instance);
    partial void Updatekehubiao(kehubiao instance);
    partial void Deletekehubiao(kehubiao instance);
    partial void InsertCmoney(Cmoney instance);
    partial void UpdateCmoney(Cmoney instance);
    partial void DeleteCmoney(Cmoney instance);
    #endregion
		
		public bookDataContext() : 
				base(global::book.DAL.Properties.Settings.Default.bookConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<leixingbiao> leixingbiao
		{
			get
			{
				return this.GetTable<leixingbiao>();
			}
		}
		
		public System.Data.Linq.Table<log> log
		{
			get
			{
				return this.GetTable<log>();
			}
		}
		
		public System.Data.Linq.Table<jiehuanbiao> jiehuanbiao
		{
			get
			{
				return this.GetTable<jiehuanbiao>();
			}
		}
		
		public System.Data.Linq.Table<tushubiao> tushubiao
		{
			get
			{
				return this.GetTable<tushubiao>();
			}
		}
		
		public System.Data.Linq.Table<cuihuanbiao> cuihuanbiao
		{
			get
			{
				return this.GetTable<cuihuanbiao>();
			}
		}

		public System.Data.Linq.Table<Customer> Customer
        {
			get
			{
				return this.GetTable<Customer>();
			}
		}

		public System.Data.Linq.Table<kehubiao> kehubiao
		{
			get
			{
				return this.GetTable<kehubiao>();
			}
		}
		
		public System.Data.Linq.Table<Cmoney> Cmoney
		{
			get
			{
				return this.GetTable<Cmoney>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.leixingbiao")]
	public partial class leixingbiao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _l_id;
		
		private string _l_leixing;
		
		private int _l_qixian;
		
		private string _l_miaoshu;
		
		private EntitySet<tushubiao> _tushubiao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onl_idChanging(int value);
    partial void Onl_idChanged();
    partial void Onl_leixingChanging(string value);
    partial void Onl_leixingChanged();
    partial void Onl_qixianChanging(int value);
    partial void Onl_qixianChanged();
    partial void Onl_miaoshuChanging(string value);
    partial void Onl_miaoshuChanged();
    #endregion
		
		public leixingbiao()
		{
			this._tushubiao = new EntitySet<tushubiao>(new Action<tushubiao>(this.attach_tushubiao), new Action<tushubiao>(this.detach_tushubiao));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int l_id
		{
			get
			{
				return this._l_id;
			}
			set
			{
				if ((this._l_id != value))
				{
					this.Onl_idChanging(value);
					this.SendPropertyChanging();
					this._l_id = value;
					this.SendPropertyChanged("l_id");
					this.Onl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_leixing", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string l_leixing
		{
			get
			{
				return this._l_leixing;
			}
			set
			{
				if ((this._l_leixing != value))
				{
					this.Onl_leixingChanging(value);
					this.SendPropertyChanging();
					this._l_leixing = value;
					this.SendPropertyChanged("l_leixing");
					this.Onl_leixingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_qixian", DbType="Int NOT NULL")]
		public int l_qixian
		{
			get
			{
				return this._l_qixian;
			}
			set
			{
				if ((this._l_qixian != value))
				{
					this.Onl_qixianChanging(value);
					this.SendPropertyChanging();
					this._l_qixian = value;
					this.SendPropertyChanged("l_qixian");
					this.Onl_qixianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_miaoshu", DbType="NVarChar(500)")]
		public string l_miaoshu
		{
			get
			{
				return this._l_miaoshu;
			}
			set
			{
				if ((this._l_miaoshu != value))
				{
					this.Onl_miaoshuChanging(value);
					this.SendPropertyChanging();
					this._l_miaoshu = value;
					this.SendPropertyChanged("l_miaoshu");
					this.Onl_miaoshuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="leixingbiao_tushubiao", Storage="_tushubiao", ThisKey="l_id", OtherKey="l_id")]
		public EntitySet<tushubiao> tushubiao
		{
			get
			{
				return this._tushubiao;
			}
			set
			{
				this._tushubiao.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tushubiao(tushubiao entity)
		{
			this.SendPropertyChanging();
			entity.leixingbiao = this;
		}
		
		private void detach_tushubiao(tushubiao entity)
		{
			this.SendPropertyChanging();
			entity.leixingbiao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[log]")]
	public partial class log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _log_id;
		
		private string _username;
		
		private string _type;
		
		private System.DateTime _action_date;
		
		private string _action_table;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onaction_dateChanging(System.DateTime value);
    partial void Onaction_dateChanged();
    partial void Onaction_tableChanging(string value);
    partial void Onaction_tableChanged();
    #endregion
		
		public log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action_date", DbType="Date NOT NULL")]
		public System.DateTime action_date
		{
			get
			{
				return this._action_date;
			}
			set
			{
				if ((this._action_date != value))
				{
					this.Onaction_dateChanging(value);
					this.SendPropertyChanging();
					this._action_date = value;
					this.SendPropertyChanged("action_date");
					this.Onaction_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action_table", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string action_table
		{
			get
			{
				return this._action_table;
			}
			set
			{
				if ((this._action_table != value))
				{
					this.Onaction_tableChanging(value);
					this.SendPropertyChanging();
					this._action_table = value;
					this.SendPropertyChanged("action_table");
					this.Onaction_tableChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jiehuanbiao")]
	public partial class jiehuanbiao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _j_id;
		
		private int _t_id;
		
		private System.Nullable<int> _k_id;
		
		private System.DateTime _j_jiechu;
		
		private System.Nullable<System.DateTime> _j_huan;
		
		private string _j_beizhu;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _j_yingh;
		
		private string _j_zhuangtai;
		
		private System.Nullable<int> _c_id;
		
		private EntityRef<tushubiao> _tushubiao;
		
		private EntityRef<Customer> _Customer;
		
		private EntityRef<kehubiao> _kehubiao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onj_idChanging(int value);
    partial void Onj_idChanged();
    partial void Ont_idChanging(int value);
    partial void Ont_idChanged();
    partial void Onk_idChanging(System.Nullable<int> value);
    partial void Onk_idChanged();
    partial void Onj_jiechuChanging(System.DateTime value);
    partial void Onj_jiechuChanged();
    partial void Onj_huanChanging(System.Nullable<System.DateTime> value);
    partial void Onj_huanChanged();
    partial void Onj_beizhuChanging(string value);
    partial void Onj_beizhuChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onj_yinghChanging(System.Nullable<System.DateTime> value);
    partial void Onj_yinghChanged();
    partial void Onj_zhuangtaiChanging(string value);
    partial void Onj_zhuangtaiChanged();
    partial void Onc_idChanging(System.Nullable<int> value);
    partial void Onc_idChanged();
    #endregion
		
		public jiehuanbiao()
		{
			this._tushubiao = default(EntityRef<tushubiao>);
			this._Customer = default(EntityRef<Customer>);
			this._kehubiao = default(EntityRef<kehubiao>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int j_id
		{
			get
			{
				return this._j_id;
			}
			set
			{
				if ((this._j_id != value))
				{
					this.Onj_idChanging(value);
					this.SendPropertyChanging();
					this._j_id = value;
					this.SendPropertyChanged("j_id");
					this.Onj_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_id", DbType="Int NOT NULL")]
		public int t_id
		{
			get
			{
				return this._t_id;
			}
			set
			{
				if ((this._t_id != value))
				{
					if (this._tushubiao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ont_idChanging(value);
					this.SendPropertyChanging();
					this._t_id = value;
					this.SendPropertyChanged("t_id");
					this.Ont_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_id", DbType="Int")]
		public System.Nullable<int> k_id
		{
			get
			{
				return this._k_id;
			}
			set
			{
				if ((this._k_id != value))
				{
					if (this._kehubiao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onk_idChanging(value);
					this.SendPropertyChanging();
					this._k_id = value;
					this.SendPropertyChanged("k_id");
					this.Onk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_jiechu", DbType="Date NOT NULL")]
		public System.DateTime j_jiechu
		{
			get
			{
				return this._j_jiechu;
			}
			set
			{
				if ((this._j_jiechu != value))
				{
					this.Onj_jiechuChanging(value);
					this.SendPropertyChanging();
					this._j_jiechu = value;
					this.SendPropertyChanged("j_jiechu");
					this.Onj_jiechuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_huan", DbType="Date")]
		public System.Nullable<System.DateTime> j_huan
		{
			get
			{
				return this._j_huan;
			}
			set
			{
				if ((this._j_huan != value))
				{
					this.Onj_huanChanging(value);
					this.SendPropertyChanging();
					this._j_huan = value;
					this.SendPropertyChanged("j_huan");
					this.Onj_huanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_beizhu", DbType="NVarChar(150)")]
		public string j_beizhu
		{
			get
			{
				return this._j_beizhu;
			}
			set
			{
				if ((this._j_beizhu != value))
				{
					this.Onj_beizhuChanging(value);
					this.SendPropertyChanging();
					this._j_beizhu = value;
					this.SendPropertyChanged("j_beizhu");
					this.Onj_beizhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_yingh", DbType="Date")]
		public System.Nullable<System.DateTime> j_yingh
		{
			get
			{
				return this._j_yingh;
			}
			set
			{
				if ((this._j_yingh != value))
				{
					this.Onj_yinghChanging(value);
					this.SendPropertyChanging();
					this._j_yingh = value;
					this.SendPropertyChanged("j_yingh");
					this.Onj_yinghChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_zhuangtai", DbType="NVarChar(50)")]
		public string j_zhuangtai
		{
			get
			{
				return this._j_zhuangtai;
			}
			set
			{
				if ((this._j_zhuangtai != value))
				{
					this.Onj_zhuangtaiChanging(value);
					this.SendPropertyChanging();
					this._j_zhuangtai = value;
					this.SendPropertyChanged("j_zhuangtai");
					this.Onj_zhuangtaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int")]
		public System.Nullable<int> c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tushubiao_jiehuanbiao", Storage="_tushubiao", ThisKey="t_id", OtherKey="t_id", IsForeignKey=true)]
		public tushubiao tushubiao
		{
			get
			{
				return this._tushubiao.Entity;
			}
			set
			{
				tushubiao previousValue = this._tushubiao.Entity;
				if (((previousValue != value) 
							|| (this._tushubiao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tushubiao.Entity = null;
						previousValue.jiehuanbiao.Remove(this);
					}
					this._tushubiao.Entity = value;
					if ((value != null))
					{
						value.jiehuanbiao.Add(this);
						this._t_id = value.t_id;
					}
					else
					{
						this._t_id = default(int);
					}
					this.SendPropertyChanged("tushubiao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_jiehuanbiao", Storage="_Customer", ThisKey="c_id", OtherKey="customerId", IsForeignKey=true)]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.jiehuanbiao.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.jiehuanbiao.Add(this);
						this._c_id = value.customerId;
					}
					else
					{
						this._c_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kehubiao_jiehuanbiao", Storage="_kehubiao", ThisKey="k_id", OtherKey="k_id", IsForeignKey=true)]
		public kehubiao kehubiao
		{
			get
			{
				return this._kehubiao.Entity;
			}
			set
			{
				kehubiao previousValue = this._kehubiao.Entity;
				if (((previousValue != value) 
							|| (this._kehubiao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kehubiao.Entity = null;
						previousValue.jiehuanbiao.Remove(this);
					}
					this._kehubiao.Entity = value;
					if ((value != null))
					{
						value.jiehuanbiao.Add(this);
						this._k_id = value.k_id;
					}
					else
					{
						this._k_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("kehubiao");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tushubiao")]
	public partial class tushubiao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _t_id;
		
		private string _ISBN;
		
		private string _s_shuming;
		
		private int _l_id;
		
		private string _s_zuozhe;
		
		private string _s_chubanshe;
		
		private System.Nullable<System.DateTime> _s_cbriqi;
		
		private System.Nullable<decimal> _s_danjia;
		
		private string _s_img;
		
		private string _s_jianjie;
		
		private System.Nullable<int> _s_cishu;
		
		private System.Nullable<int> _s_kucun;
		
		private System.Nullable<int> _s_yijie;
		
		private string _s_tjimg;
		
		private EntitySet<jiehuanbiao> _jiehuanbiao;
		
		private EntitySet<cuihuanbiao> _cuihuanbiao;
		
		private EntityRef<leixingbiao> _leixingbiao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ont_idChanging(int value);
    partial void Ont_idChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void Ons_shumingChanging(string value);
    partial void Ons_shumingChanged();
    partial void Onl_idChanging(int value);
    partial void Onl_idChanged();
    partial void Ons_zuozheChanging(string value);
    partial void Ons_zuozheChanged();
    partial void Ons_chubansheChanging(string value);
    partial void Ons_chubansheChanged();
    partial void Ons_cbriqiChanging(System.Nullable<System.DateTime> value);
    partial void Ons_cbriqiChanged();
    partial void Ons_danjiaChanging(System.Nullable<decimal> value);
    partial void Ons_danjiaChanged();
    partial void Ons_imgChanging(string value);
    partial void Ons_imgChanged();
    partial void Ons_jianjieChanging(string value);
    partial void Ons_jianjieChanged();
    partial void Ons_cishuChanging(System.Nullable<int> value);
    partial void Ons_cishuChanged();
    partial void Ons_kucunChanging(System.Nullable<int> value);
    partial void Ons_kucunChanged();
    partial void Ons_yijieChanging(System.Nullable<int> value);
    partial void Ons_yijieChanged();
    partial void Ons_tjimgChanging(string value);
    partial void Ons_tjimgChanged();
    #endregion
		
		public tushubiao()
		{
			this._jiehuanbiao = new EntitySet<jiehuanbiao>(new Action<jiehuanbiao>(this.attach_jiehuanbiao), new Action<jiehuanbiao>(this.detach_jiehuanbiao));
			this._cuihuanbiao = new EntitySet<cuihuanbiao>(new Action<cuihuanbiao>(this.attach_cuihuanbiao), new Action<cuihuanbiao>(this.detach_cuihuanbiao));
			this._leixingbiao = default(EntityRef<leixingbiao>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int t_id
		{
			get
			{
				return this._t_id;
			}
			set
			{
				if ((this._t_id != value))
				{
					this.Ont_idChanging(value);
					this.SendPropertyChanging();
					this._t_id = value;
					this.SendPropertyChanged("t_id");
					this.Ont_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_shuming", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string s_shuming
		{
			get
			{
				return this._s_shuming;
			}
			set
			{
				if ((this._s_shuming != value))
				{
					this.Ons_shumingChanging(value);
					this.SendPropertyChanging();
					this._s_shuming = value;
					this.SendPropertyChanged("s_shuming");
					this.Ons_shumingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_id", DbType="Int NOT NULL")]
		public int l_id
		{
			get
			{
				return this._l_id;
			}
			set
			{
				if ((this._l_id != value))
				{
					if (this._leixingbiao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onl_idChanging(value);
					this.SendPropertyChanging();
					this._l_id = value;
					this.SendPropertyChanged("l_id");
					this.Onl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_zuozhe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string s_zuozhe
		{
			get
			{
				return this._s_zuozhe;
			}
			set
			{
				if ((this._s_zuozhe != value))
				{
					this.Ons_zuozheChanging(value);
					this.SendPropertyChanging();
					this._s_zuozhe = value;
					this.SendPropertyChanged("s_zuozhe");
					this.Ons_zuozheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_chubanshe", DbType="NVarChar(50)")]
		public string s_chubanshe
		{
			get
			{
				return this._s_chubanshe;
			}
			set
			{
				if ((this._s_chubanshe != value))
				{
					this.Ons_chubansheChanging(value);
					this.SendPropertyChanging();
					this._s_chubanshe = value;
					this.SendPropertyChanged("s_chubanshe");
					this.Ons_chubansheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_cbriqi", DbType="Date")]
		public System.Nullable<System.DateTime> s_cbriqi
		{
			get
			{
				return this._s_cbriqi;
			}
			set
			{
				if ((this._s_cbriqi != value))
				{
					this.Ons_cbriqiChanging(value);
					this.SendPropertyChanging();
					this._s_cbriqi = value;
					this.SendPropertyChanged("s_cbriqi");
					this.Ons_cbriqiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_danjia", DbType="Money")]
		public System.Nullable<decimal> s_danjia
		{
			get
			{
				return this._s_danjia;
			}
			set
			{
				if ((this._s_danjia != value))
				{
					this.Ons_danjiaChanging(value);
					this.SendPropertyChanging();
					this._s_danjia = value;
					this.SendPropertyChanged("s_danjia");
					this.Ons_danjiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_img", DbType="NVarChar(100)")]
		public string s_img
		{
			get
			{
				return this._s_img;
			}
			set
			{
				if ((this._s_img != value))
				{
					this.Ons_imgChanging(value);
					this.SendPropertyChanging();
					this._s_img = value;
					this.SendPropertyChanged("s_img");
					this.Ons_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_jianjie", DbType="NVarChar(1550)")]
		public string s_jianjie
		{
			get
			{
				return this._s_jianjie;
			}
			set
			{
				if ((this._s_jianjie != value))
				{
					this.Ons_jianjieChanging(value);
					this.SendPropertyChanging();
					this._s_jianjie = value;
					this.SendPropertyChanged("s_jianjie");
					this.Ons_jianjieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_cishu", DbType="Int")]
		public System.Nullable<int> s_cishu
		{
			get
			{
				return this._s_cishu;
			}
			set
			{
				if ((this._s_cishu != value))
				{
					this.Ons_cishuChanging(value);
					this.SendPropertyChanging();
					this._s_cishu = value;
					this.SendPropertyChanged("s_cishu");
					this.Ons_cishuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_kucun", DbType="Int")]
		public System.Nullable<int> s_kucun
		{
			get
			{
				return this._s_kucun;
			}
			set
			{
				if ((this._s_kucun != value))
				{
					this.Ons_kucunChanging(value);
					this.SendPropertyChanging();
					this._s_kucun = value;
					this.SendPropertyChanged("s_kucun");
					this.Ons_kucunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_yijie", DbType="Int")]
		public System.Nullable<int> s_yijie
		{
			get
			{
				return this._s_yijie;
			}
			set
			{
				if ((this._s_yijie != value))
				{
					this.Ons_yijieChanging(value);
					this.SendPropertyChanging();
					this._s_yijie = value;
					this.SendPropertyChanged("s_yijie");
					this.Ons_yijieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_tjimg", DbType="NVarChar(200)")]
		public string s_tjimg
		{
			get
			{
				return this._s_tjimg;
			}
			set
			{
				if ((this._s_tjimg != value))
				{
					this.Ons_tjimgChanging(value);
					this.SendPropertyChanging();
					this._s_tjimg = value;
					this.SendPropertyChanged("s_tjimg");
					this.Ons_tjimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tushubiao_jiehuanbiao", Storage="_jiehuanbiao", ThisKey="t_id", OtherKey="t_id")]
		public EntitySet<jiehuanbiao> jiehuanbiao
		{
			get
			{
				return this._jiehuanbiao;
			}
			set
			{
				this._jiehuanbiao.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tushubiao_cuihuanbiao", Storage="_cuihuanbiao", ThisKey="t_id", OtherKey="t_id")]
		public EntitySet<cuihuanbiao> cuihuanbiao
		{
			get
			{
				return this._cuihuanbiao;
			}
			set
			{
				this._cuihuanbiao.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="leixingbiao_tushubiao", Storage="_leixingbiao", ThisKey="l_id", OtherKey="l_id", IsForeignKey=true)]
		public leixingbiao leixingbiao
		{
			get
			{
				return this._leixingbiao.Entity;
			}
			set
			{
				leixingbiao previousValue = this._leixingbiao.Entity;
				if (((previousValue != value) 
							|| (this._leixingbiao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._leixingbiao.Entity = null;
						previousValue.tushubiao.Remove(this);
					}
					this._leixingbiao.Entity = value;
					if ((value != null))
					{
						value.tushubiao.Add(this);
						this._l_id = value.l_id;
					}
					else
					{
						this._l_id = default(int);
					}
					this.SendPropertyChanged("leixingbiao");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_jiehuanbiao(jiehuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.tushubiao = this;
		}
		
		private void detach_jiehuanbiao(jiehuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.tushubiao = null;
		}
		
		private void attach_cuihuanbiao(cuihuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.tushubiao = this;
		}
		
		private void detach_cuihuanbiao(cuihuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.tushubiao = null;
		}

        public object SelectLeaguerInfo(string t_id1)
        {
            throw new NotImplementedException();
        }

        public DataSet SelectBookInfo()
        {
            throw new NotImplementedException();
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cuihuanbiao")]
	public partial class cuihuanbiao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _c_id;
		
		private int _t_id;
		
		private int _k_id;
		
		private System.DateTime _c_riqi;
		
		private string _c_neirong;
		
		private string _c_beizhu;
		
		private string _c_name;
		
		private EntityRef<tushubiao> _tushubiao;
		
		private EntityRef<kehubiao> _kehubiao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Ont_idChanging(int value);
    partial void Ont_idChanged();
    partial void Onk_idChanging(int value);
    partial void Onk_idChanged();
    partial void Onc_riqiChanging(System.DateTime value);
    partial void Onc_riqiChanged();
    partial void Onc_neirongChanging(string value);
    partial void Onc_neirongChanged();
    partial void Onc_beizhuChanging(string value);
    partial void Onc_beizhuChanged();
    partial void Onc_nameChanging(string value);
    partial void Onc_nameChanged();
    #endregion
		
		public cuihuanbiao()
		{
			this._tushubiao = default(EntityRef<tushubiao>);
			this._kehubiao = default(EntityRef<kehubiao>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_id", DbType="Int NOT NULL")]
		public int t_id
		{
			get
			{
				return this._t_id;
			}
			set
			{
				if ((this._t_id != value))
				{
					if (this._tushubiao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ont_idChanging(value);
					this.SendPropertyChanging();
					this._t_id = value;
					this.SendPropertyChanged("t_id");
					this.Ont_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_id", DbType="Int NOT NULL")]
		public int k_id
		{
			get
			{
				return this._k_id;
			}
			set
			{
				if ((this._k_id != value))
				{
					if (this._kehubiao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onk_idChanging(value);
					this.SendPropertyChanging();
					this._k_id = value;
					this.SendPropertyChanged("k_id");
					this.Onk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_riqi", DbType="Date NOT NULL")]
		public System.DateTime c_riqi
		{
			get
			{
				return this._c_riqi;
			}
			set
			{
				if ((this._c_riqi != value))
				{
					this.Onc_riqiChanging(value);
					this.SendPropertyChanging();
					this._c_riqi = value;
					this.SendPropertyChanged("c_riqi");
					this.Onc_riqiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_neirong", DbType="NVarChar(550)")]
		public string c_neirong
		{
			get
			{
				return this._c_neirong;
			}
			set
			{
				if ((this._c_neirong != value))
				{
					this.Onc_neirongChanging(value);
					this.SendPropertyChanging();
					this._c_neirong = value;
					this.SendPropertyChanged("c_neirong");
					this.Onc_neirongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_beizhu", DbType="NVarChar(150)")]
		public string c_beizhu
		{
			get
			{
				return this._c_beizhu;
			}
			set
			{
				if ((this._c_beizhu != value))
				{
					this.Onc_beizhuChanging(value);
					this.SendPropertyChanging();
					this._c_beizhu = value;
					this.SendPropertyChanged("c_beizhu");
					this.Onc_beizhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="NVarChar(50)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this.Onc_nameChanging(value);
					this.SendPropertyChanging();
					this._c_name = value;
					this.SendPropertyChanged("c_name");
					this.Onc_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tushubiao_cuihuanbiao", Storage="_tushubiao", ThisKey="t_id", OtherKey="t_id", IsForeignKey=true)]
		public tushubiao tushubiao
		{
			get
			{
				return this._tushubiao.Entity;
			}
			set
			{
				tushubiao previousValue = this._tushubiao.Entity;
				if (((previousValue != value) 
							|| (this._tushubiao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tushubiao.Entity = null;
						previousValue.cuihuanbiao.Remove(this);
					}
					this._tushubiao.Entity = value;
					if ((value != null))
					{
						value.cuihuanbiao.Add(this);
						this._t_id = value.t_id;
					}
					else
					{
						this._t_id = default(int);
					}
					this.SendPropertyChanged("tushubiao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kehubiao_cuihuanbiao", Storage="_kehubiao", ThisKey="k_id", OtherKey="k_id", IsForeignKey=true)]
		public kehubiao kehubiao
		{
			get
			{
				return this._kehubiao.Entity;
			}
			set
			{
				kehubiao previousValue = this._kehubiao.Entity;
				if (((previousValue != value) 
							|| (this._kehubiao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kehubiao.Entity = null;
						previousValue.cuihuanbiao.Remove(this);
					}
					this._kehubiao.Entity = value;
					if ((value != null))
					{
						value.cuihuanbiao.Add(this);
						this._k_id = value.k_id;
					}
					else
					{
						this._k_id = default(int);
					}
					this.SendPropertyChanged("kehubiao");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _customerId;
		
		private string _name;
		
		private string _password;
		
		private string _email;
		
		private System.Nullable<int> _age;
		
		private EntitySet<jiehuanbiao> _jiehuanbiao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncustomerIdChanging(int value);
    partial void OncustomerIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    #endregion
		
		public Customer()
		{
			this._jiehuanbiao = new EntitySet<jiehuanbiao>(new Action<jiehuanbiao>(this.attach_jiehuanbiao), new Action<jiehuanbiao>(this.detach_jiehuanbiao));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int customerId
		{
			get
			{
				return this._customerId;
			}
			set
			{
				if ((this._customerId != value))
				{
					this.OncustomerIdChanging(value);
					this.SendPropertyChanging();
					this._customerId = value;
					this.SendPropertyChanged("customerId");
					this.OncustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_jiehuanbiao", Storage="_jiehuanbiao", ThisKey="customerId", OtherKey="c_id")]
		public EntitySet<jiehuanbiao> jiehuanbiao
		{
			get
			{
				return this._jiehuanbiao;
			}
			set
			{
				this._jiehuanbiao.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_jiehuanbiao(jiehuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_jiehuanbiao(jiehuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kehubiao")]
	public partial class kehubiao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _k_id;
		
		private string _k_xingming;
		
		private string _k_Email;
		
		private System.Nullable<int> _k_age;
		
		private EntitySet<jiehuanbiao> _jiehuanbiao;
		
		private EntitySet<cuihuanbiao> _cuihuanbiao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onk_idChanging(int value);
    partial void Onk_idChanged();
    partial void Onk_xingmingChanging(string value);
    partial void Onk_xingmingChanged();
    partial void Onk_EmailChanging(string value);
    partial void Onk_EmailChanged();
    partial void Onk_ageChanging(System.Nullable<int> value);
    partial void Onk_ageChanged();
    #endregion
		
		public kehubiao()
		{
			this._jiehuanbiao = new EntitySet<jiehuanbiao>(new Action<jiehuanbiao>(this.attach_jiehuanbiao), new Action<jiehuanbiao>(this.detach_jiehuanbiao));
			this._cuihuanbiao = new EntitySet<cuihuanbiao>(new Action<cuihuanbiao>(this.attach_cuihuanbiao), new Action<cuihuanbiao>(this.detach_cuihuanbiao));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int k_id
		{
			get
			{
				return this._k_id;
			}
			set
			{
				if ((this._k_id != value))
				{
					this.Onk_idChanging(value);
					this.SendPropertyChanging();
					this._k_id = value;
					this.SendPropertyChanged("k_id");
					this.Onk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_xingming", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string k_xingming
		{
			get
			{
				return this._k_xingming;
			}
			set
			{
				if ((this._k_xingming != value))
				{
					this.Onk_xingmingChanging(value);
					this.SendPropertyChanging();
					this._k_xingming = value;
					this.SendPropertyChanged("k_xingming");
					this.Onk_xingmingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_Email", DbType="NVarChar(50)")]
		public string k_Email
		{
			get
			{
				return this._k_Email;
			}
			set
			{
				if ((this._k_Email != value))
				{
					this.Onk_EmailChanging(value);
					this.SendPropertyChanging();
					this._k_Email = value;
					this.SendPropertyChanged("k_Email");
					this.Onk_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_age", DbType="Int")]
		public System.Nullable<int> k_age
		{
			get
			{
				return this._k_age;
			}
			set
			{
				if ((this._k_age != value))
				{
					this.Onk_ageChanging(value);
					this.SendPropertyChanging();
					this._k_age = value;
					this.SendPropertyChanged("k_age");
					this.Onk_ageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kehubiao_jiehuanbiao", Storage="_jiehuanbiao", ThisKey="k_id", OtherKey="k_id")]
		public EntitySet<jiehuanbiao> jiehuanbiao
		{
			get
			{
				return this._jiehuanbiao;
			}
			set
			{
				this._jiehuanbiao.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kehubiao_cuihuanbiao", Storage="_cuihuanbiao", ThisKey="k_id", OtherKey="k_id")]
		public EntitySet<cuihuanbiao> cuihuanbiao
		{
			get
			{
				return this._cuihuanbiao;
			}
			set
			{
				this._cuihuanbiao.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_jiehuanbiao(jiehuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.kehubiao = this;
		}
		
		private void detach_jiehuanbiao(jiehuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.kehubiao = null;
		}
		
		private void attach_cuihuanbiao(cuihuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.kehubiao = this;
		}
		
		private void detach_cuihuanbiao(cuihuanbiao entity)
		{
			this.SendPropertyChanging();
			entity.kehubiao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cmoney")]
	public partial class Cmoney : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _m_id;
		
		private string _s_shuming;
		
		private System.Nullable<decimal> _s_danjia;
		
		private string _name;
		
		private decimal _moneys;
		
		private string _m_zhuangtai;
		
		private string _m_leixing;
		
		private System.Nullable<System.DateTime> _m_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onm_idChanging(int value);
    partial void Onm_idChanged();
    partial void Ons_shumingChanging(string value);
    partial void Ons_shumingChanged();
    partial void Ons_danjiaChanging(System.Nullable<decimal> value);
    partial void Ons_danjiaChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmoneysChanging(decimal value);
    partial void OnmoneysChanged();
    partial void Onm_zhuangtaiChanging(string value);
    partial void Onm_zhuangtaiChanged();
    partial void Onm_leixingChanging(string value);
    partial void Onm_leixingChanged();
    partial void Onm_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onm_timeChanged();
    #endregion
		
		public Cmoney()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int m_id
		{
			get
			{
				return this._m_id;
			}
			set
			{
				if ((this._m_id != value))
				{
					this.Onm_idChanging(value);
					this.SendPropertyChanging();
					this._m_id = value;
					this.SendPropertyChanged("m_id");
					this.Onm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_shuming", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string s_shuming
		{
			get
			{
				return this._s_shuming;
			}
			set
			{
				if ((this._s_shuming != value))
				{
					this.Ons_shumingChanging(value);
					this.SendPropertyChanging();
					this._s_shuming = value;
					this.SendPropertyChanged("s_shuming");
					this.Ons_shumingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_danjia", DbType="Money")]
		public System.Nullable<decimal> s_danjia
		{
			get
			{
				return this._s_danjia;
			}
			set
			{
				if ((this._s_danjia != value))
				{
					this.Ons_danjiaChanging(value);
					this.SendPropertyChanging();
					this._s_danjia = value;
					this.SendPropertyChanged("s_danjia");
					this.Ons_danjiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moneys", DbType="Money NOT NULL")]
		public decimal moneys
		{
			get
			{
				return this._moneys;
			}
			set
			{
				if ((this._moneys != value))
				{
					this.OnmoneysChanging(value);
					this.SendPropertyChanging();
					this._moneys = value;
					this.SendPropertyChanged("moneys");
					this.OnmoneysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_zhuangtai", DbType="NVarChar(50)")]
		public string m_zhuangtai
		{
			get
			{
				return this._m_zhuangtai;
			}
			set
			{
				if ((this._m_zhuangtai != value))
				{
					this.Onm_zhuangtaiChanging(value);
					this.SendPropertyChanging();
					this._m_zhuangtai = value;
					this.SendPropertyChanged("m_zhuangtai");
					this.Onm_zhuangtaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_leixing", DbType="NVarChar(50)")]
		public string m_leixing
		{
			get
			{
				return this._m_leixing;
			}
			set
			{
				if ((this._m_leixing != value))
				{
					this.Onm_leixingChanging(value);
					this.SendPropertyChanging();
					this._m_leixing = value;
					this.SendPropertyChanged("m_leixing");
					this.Onm_leixingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_time", DbType="Date")]
		public System.Nullable<System.DateTime> m_time
		{
			get
			{
				return this._m_time;
			}
			set
			{
				if ((this._m_time != value))
				{
					this.Onm_timeChanging(value);
					this.SendPropertyChanging();
					this._m_time = value;
					this.SendPropertyChanged("m_time");
					this.Onm_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
